// =============================================================================
// 特別支援学校小学部 国語科（1〜3段階）指導要領解説 完全準拠データ
// =============================================================================

window.DATA_KOKUGO = [
  // --- 第1段階 (16項目) ---
  { id: "K1_K_1_A", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)ア", text: "身近な人の話し掛けに慣れ，言葉が事物の内容を表していることを感じること。" },
  { id: "K1_K_1_B", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)イ", text: "言葉のもつ音やリズムに触れたり，言葉が表す事物やイメージに触れたりすること。" },
  { id: "K1_K_2_A", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ア", text: "昔話などについて，読み聞かせを聞くなどして親しむこと。" },
  { id: "K1_K_2_B", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)イ", text: "遊びを通して，言葉のもつ楽しさに触れること。" },
  { id: "K1_K_2_C_A", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋐", text: "いろいろな筆記具に触れ，書くことを知ること。" },
  { id: "K1_K_2_C_B", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋑", text: "筆記具の持ち方や，正しい姿勢で書くことを知ること。" },
  { id: "K1_K_2_D", sub: "国語", stage: 1, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)エ", text: "読み聞かせに注目したり，いろいろな絵本などに興味をもったりすること。" },
  { id: "K1_S_A", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ア", text: "身近な人の話に慣れ，音声を模倣したり，表情や身振り，簡単な話し言葉などで表現したりすること。" },
  { id: "K1_S_B", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと イ", text: "身近な人からの話し掛けに注目したり，応じて答えたりすること。" },
  { id: "K1_S_C", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ウ", text: "伝えたいことを思い浮かべ，身振りや音声などで表すこと。" },
  { id: "K1_W_A", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと ア", text: "身近な人との関わりや出来事について，伝えたいことを思い浮かべたり，選んだりすること。" },
  { id: "K1_W_B", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと イ", text: "文字に興味をもち，書こうとすること。" },
  { id: "K1_R_A", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ア", text: "教師と一緒に絵本などを見て，示された身近な事物や生き物などに気付き，注目すること。" },
  { id: "K1_R_B", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと イ", text: "絵本などを見て，知っている事物や出来事などを指さしなどで表現すること。" },
  { id: "K1_R_C", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ウ", text: "絵や矢印などの記号で表された意味に応じ，行動すること。" },
  { id: "K1_R_D", sub: "国語", stage: 1, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと エ", text: "絵本などを見て，次の場面を楽しみにしたり，登場人物の動きなどを模倣したりすること。" },

  // --- 第2段階 (18項目) ---
  { id: "K2_K_1_A", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)ア", text: "身近な人の話し掛けや会話などの話し言葉に慣れ，言葉が，気持ちや要求を表していることを感じること。" },
  { id: "K2_K_1_B", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)イ", text: "日常生活でよく使われている平仮名を読むこと。" },
  { id: "K2_K_1_C", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)ウ", text: "身近な人との会話を通して，物の名前や動作など，いろいろな言葉の種類に触れること。" },
  { id: "K2_K_2_A", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ア", text: "昔話や童謡の読み聞かせを聞き，模倣したり言葉の響きやリズムに親しんだりすること。" },
  { id: "K2_K_2_B", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)イ", text: "遊びややり取りを通して，言葉による表現に親しむこと。" },
  { id: "K2_K_2_C_A", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋐", text: "いろいろな筆記具を用いて，書くことに親しむこと。" },
  { id: "K2_K_2_C_B", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋑", text: "写し書きやなぞり書きなどにより，書写の基本を身に付けること。" },
  { id: "K2_K_2_D", sub: "国語", stage: 2, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)エ", text: "読み聞かせに親しみ，文字を拾い読みして絵本や図鑑などに興味をもつこと。" },
  { id: "K2_S_A", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ア", text: "身近な人の話に慣れ，簡単な事柄と語句を結び付け思い浮かべること。" },
  { id: "K2_S_B", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと イ", text: "簡単な指示や説明を聞き，その指示等に応じた行動をすること。" },
  { id: "K2_S_C", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ウ", text: "体験したことなどについて，伝えたいことを考えること。" },
  { id: "K2_S_D", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと エ", text: "挨拶をしたり，簡単な台詞などを表現したりすること。" },
  { id: "K2_W_A", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと ア", text: "経験したことのうち身近なことについて，写真などを手掛かりにして，伝えたいことを思い浮かべたり，選んだりすること。" },
  { id: "K2_W_B", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと イ", text: "自分の名前や物の名前を文字で表すことができることを知り，簡単な平仮名をなぞったり，書いたりすること。" },
  { id: "K2_R_A", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ア", text: "教師と一緒に絵本などを見て，登場するものや動作などを思い浮かべること。" },
  { id: "K2_R_B", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと イ", text: "教師と一緒に絵本などを見て，時間の経過などの大体を捉えること。" },
  { id: "K2_R_C", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ウ", text: "日常生活でよく使われている表示などの特徴に気付き，読もうとしたり，表された意味に応じた行動をしたりすること。" },
  { id: "K2_R_D", sub: "国語", stage: 2, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと エ", text: "絵本などを見て，好きな場面を伝えたり，言葉などを模倣したりすること。" },

  // --- 第3段階 (28項目) ---
  { id: "K3_K_1_A", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)ア", text: "身近な人との会話や読み聞かせを通して，言葉には物事の内容を表す働きがあることに気付くこと。" },
  { id: "K3_K_1_B", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)イ", text: "姿勢や口形に気を付けて話すこと。" },
  { id: "K3_K_1_C", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)ウ", text: "日常生活でよく使う促音，長音などが含まれた語句，平仮名，片仮名，漢字の正しい読み方を知ること。" },
  { id: "K3_K_1_D", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)エ", text: "言葉には，意味による語句のまとまりがあることに気付くこと。" },
  { id: "K3_K_1_E", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)オ", text: "文の中における主語と述語との関係や助詞の使い方により，意味が変わることを知ること。" },
  { id: "K3_K_1_F", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(1)カ", text: "正しい姿勢で音読すること。" },
  { id: "K3_K_2_A", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(2)ア", text: "物事の始めと終わりなど，情報と情報との関係について理解すること。" },
  { id: "K3_K_2_B", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(2)イ", text: "図書を用いた調べ方を理解し使うこと。" },
  { id: "K3_K_3_A", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ア", text: "昔話や神話・伝承などの読み聞かせを聞き，言葉の響きやリズムに親しむこと。" },
  { id: "K3_K_3_B", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)イ", text: "出来事や経験を伝え合う体験を通し，多様な語句や文表現に触れること。" },
  { id: "K3_K_3_C_A", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋐", text: "目的に合った筆記具を選び，書くこと。" },
  { id: "K3_K_3_C_B", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)ウ㋑", text: "文字の形に注意しながら平仮名や片仮名を丁寧に書くこと。" },
  { id: "K3_K_3_D", sub: "国語", stage: 3, aspect: "知識及び技能", category: "国語・知識技能", domLabel: "〔知識及び技能〕(3)エ", text: "読み聞かせなどに親しみ，多様な絵本や図鑑があることを知ること。" },
  { id: "K3_S_A", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ア", text: "絵本の読み聞かせ等を通し，出来事など話の大体を聞き取ること。" },
  { id: "K3_S_B", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと イ", text: "経験したことを思い浮かべ，伝えたいことを考えること。" },
  { id: "K3_S_C", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと ウ", text: "見聞きしたことのあらましや自分の気持ちについて思い付き考えること。" },
  { id: "K3_S_D", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと エ", text: "挨拶や電話の受け答えなど，決まった言い方を使うこと。" },
  { id: "K3_S_E", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと オ", text: "相手に伝わるよう，発音や声の大きさに気を付けること。" },
  { id: "K3_S_F", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・聞話", domLabel: "Ａ 聞くこと・話すこと カ", text: "相手の話に関心をもち，自分の思いや考えを相手に伝えたり，相手の思いや考えを受け止めたりすること。" },
  { id: "K3_W_A", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと ア", text: "身近で見聞きしたり，経験したりしたことについて書きたいことを見付け，その題材に必要な事柄を集めること。" },
  { id: "K3_W_B", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと イ", text: "見聞きしたり，経験したりしたことから，伝えたい事柄の順序を考えること。" },
  { id: "K3_W_C", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと ウ", text: "見聞きしたり，経験したりしたことについて，簡単な語句や短い文を書くこと。" },
  { id: "K3_W_D", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと エ", text: "書いた語句や文を読み，間違いを正すこと。" },
  { id: "K3_W_E", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・書く", domLabel: "Ｂ 書くこと オ", text: "文などに対して感じたことを伝えること。" },
  { id: "K3_R_A", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ア", text: "絵本や易しい読み物などを読み，挿絵と結び付けて登場人物の行動や場面の様子などを想像すること。" },
  { id: "K3_R_B", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと イ", text: "絵本や易しい読み物などを読み，時間的な順序など内容の大体を捉えること。" },
  { id: "K3_R_C", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと ウ", text: "日常生活で必要な語句や文，看板などを読み，必要な物を選んだり行動したりすること。" },
  { id: "K3_R_D", sub: "国語", stage: 3, aspect: "思考力，判断力，表現力等", category: "国語・読む", domLabel: "Ｃ 読むこと エ", text: "登場人物になったつもりで，音読したり演じたりすること。" }
];

window.STRANDS_KOKUGO = [
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "ア", items: { 1: "K1_K_1_A", 2: "K2_K_1_A", 3: "K3_K_1_A" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "イ", items: { 1: "K1_K_1_B", 2: "K2_K_1_B", 3: "K3_K_1_B" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "ウ", items: { 1: null, 2: "K2_K_1_C", 3: "K3_K_1_C" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "エ", items: { 1: null, 2: null, 3: "K3_K_1_D" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "オ", items: { 1: null, 2: null, 3: "K3_K_1_E" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(1) 言葉の特徴や使い方に関する事項", itemCode: "カ", items: { 1: null, 2: null, 3: "K3_K_1_F" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(2) 情報の扱い方に関する事項", itemCode: "ア", items: { 1: null, 2: null, 3: "K3_K_2_A" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(2) 情報の扱い方に関する事項", itemCode: "イ", items: { 1: null, 2: null, 3: "K3_K_2_B" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(3) 我が国の言語文化に関する事項", itemCode: "ア", items: { 1: "K1_K_2_A", 2: "K2_K_2_A", 3: "K3_K_3_A" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(3) 我が国の言語文化に関する事項", itemCode: "イ", items: { 1: "K1_K_2_B", 2: "K2_K_2_B", 3: "K3_K_3_B" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(3) 我が国の言語文化に関する事項", itemCode: "ウ㋐", items: { 1: "K1_K_2_C_A", 2: "K2_K_2_C_A", 3: "K3_K_3_C_A" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(3) 我が国の言語文化に関する事項", itemCode: "ウ㋑", items: { 1: "K1_K_2_C_B", 2: "K2_K_2_C_B", 3: "K3_K_3_C_B" } },
  { sub: "国語", section: "〔知識及び技能〕", domTitle: "(3) 我が国の言語文化に関する事項", itemCode: "エ", items: { 1: "K1_K_2_D", 2: "K2_K_2_D", 3: "K3_K_3_D" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "ア", items: { 1: "K1_S_A", 2: "K2_S_A", 3: "K3_S_A" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "イ", items: { 1: "K1_S_B", 2: "K2_S_B", 3: "K3_S_B" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "ウ", items: { 1: "K1_S_C", 2: "K2_S_C", 3: "K3_S_C" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "エ", items: { 1: null, 2: "K2_S_D", 3: "K3_S_D" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "オ", items: { 1: null, 2: null, 3: "K3_S_E" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ａ 聞くこと・話すこと", itemCode: "カ", items: { 1: null, 2: null, 3: "K3_S_F" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｂ 書くこと", itemCode: "ア", items: { 1: "K1_W_A", 2: "K2_W_A", 3: "K3_W_A" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｂ 書くこと", itemCode: "イ", items: { 1: "K1_W_B", 2: "K2_W_B", 3: "K3_W_B" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｂ 書くこと", itemCode: "ウ", items: { 1: null, 2: null, 3: "K3_W_C" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｂ 書くこと", itemCode: "エ", items: { 1: null, 2: null, 3: "K3_W_D" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｂ 書くこと", itemCode: "オ", items: { 1: null, 2: null, 3: "K3_W_E" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｃ 読むこと", itemCode: "ア", items: { 1: "K1_R_A", 2: "K2_R_A", 3: "K3_R_A" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｃ 読むこと", itemCode: "イ", items: { 1: "K1_R_B", 2: "K2_R_B", 3: "K3_R_B" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｃ 読むこと", itemCode: "ウ", items: { 1: "K1_R_C", 2: "K2_R_C", 3: "K3_R_C" } },
  { sub: "国語", section: "〔思考力，判断力，表現力等〕", domTitle: "Ｃ 読むこと", itemCode: "エ", items: { 1: "K1_R_D", 2: "K2_R_D", 3: "K3_R_D" } }
];